"""add notifications table

Revision ID: 4b3cb52b36dd
Revises: 064082225c20
Create Date: 2026-05-26 09:09:46.501973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b3cb52b36dd'
down_revision: Union[str, None] = '064082225c20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recipient_callsign', sa.String(length=20), nullable=False),
    sa.Column('kind', sa.Enum('REMINDER_DRAFT', 'CHECKINS_READY', 'ROSTER_DRAFT', 'DELIVERY_FAILURE', name='notificationkind'), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('link_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['recipient_callsign'], ['users.callsign'], ),
    sa.ForeignKeyConstraint(['session_id'], ['net_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notifications_recipient_read', ['recipient_callsign', 'read_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_recipient_read')

    op.drop_table('notifications')
    # ### end Alembic commands ###
