"""add reminders tables

Revision ID: 4d657143fdea
Revises: ec1d1b480b04
Create Date: 2026-04-19 13:15:10.330443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d657143fdea'
down_revision: Union[str, None] = 'ec1d1b480b04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminder_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('template_type', sa.Enum('REGULAR_CHECKIN', 'ACTIVITY', name='templatetype'), nullable=False),
    sa.Column('subject_template', sa.Text(), nullable=False),
    sa.Column('body_template', sa.Text(), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('reminder_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'SENT', 'SKIPPED', name='reminderstatus'), nullable=False),
    sa.Column('content_subject', sa.Text(), nullable=False),
    sa.Column('content_body', sa.Text(), nullable=False),
    sa.Column('drafted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['net_sessions.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['reminder_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    # ### end Alembic commands ###

    # Seed default templates
    op.execute(
        """
        INSERT INTO reminder_templates (name, template_type, subject_template, body_template, lead_time_days, is_default)
        VALUES (
            'Regular Check-in Reminder',
            'regular_checkin',
            'W0NE Winlink Net Reminder — {{ date }}',
            'Reminder: the W0NE Winlink Net check-in is this {{ day_of_week }}, {{ date }}.\n\nPlease send your check-in to w0ne@winlink.org with your name, callsign, city, county, state, and mode.\n\nNet control: {{ net_control }}\n{% if next_week_preview %}\nNext week: {{ next_week_preview }}\n{% endif %}',
            2,
            1
        )
        """
    )
    op.execute(
        """
        INSERT INTO reminder_templates (name, template_type, subject_template, body_template, lead_time_days, is_default)
        VALUES (
            'Activity Week Reminder',
            'activity',
            'W0NE Winlink Net — {{ activity_title }} — {{ date }}',
            'This {{ day_of_week }}''s W0NE Winlink Net features a special activity: **{{ activity_title }}**\n\n{{ activity_instructions }}\n\nPlease send your check-in to w0ne@winlink.org with your name, callsign, city, county, state, and mode.\n\nNet control: {{ net_control }}\n{% if next_week_preview %}\nNext week: {{ next_week_preview }}\n{% endif %}',
            2,
            1
        )
        """
    )


def downgrade() -> None:
    op.execute("DELETE FROM reminder_templates WHERE name IN ('Regular Check-in Reminder', 'Activity Week Reminder')")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reminder_logs')
    op.drop_table('reminder_templates')
    # ### end Alembic commands ###
