"""add schedule tables

Revision ID: cf2a888eb6b9
Revises: 572315038dc3
Create Date: 2026-04-16 14:24:56.583896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf2a888eb6b9'
down_revision: Union[str, None] = '572315038dc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('net_seasons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('is_week_long', sa.Boolean(), nullable=False),
    sa.Column('activity_cadence', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('net_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('grace_period_hours', sa.Float(), nullable=False),
    sa.Column('session_type', sa.Enum('REGULAR_CHECKIN', 'ACTIVITY', name='sessiontype'), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'COMPLETED', 'CANCELLED', name='sessionstatus'), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('net_control_callsign', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['net_seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('net_sessions')
    op.drop_table('net_seasons')
    # ### end Alembic commands ###
