"""update schedule for real events

Revision ID: dbf241960f48
Revises: 4d657143fdea
Create Date: 2026-04-19 21:34:15.742698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbf241960f48'
down_revision: Union[str, None] = '4d657143fdea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('net_sessions', schema=None) as batch_op:
        batch_op.alter_column('season_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('net_sessions', schema=None) as batch_op:
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('season_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
