"""add checkins and members tables

Revision ID: ec1d1b480b04
Revises: b5486865d0df
Create Date: 2026-04-17 14:30:26.937083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec1d1b480b04'
down_revision: Union[str, None] = 'b5486865d0df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('callsign', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('first_check_in_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_check_in_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_check_ins', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('callsign')
    )
    op.create_table('raw_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.String(length=255), nullable=False),
    sa.Column('from_address', sa.String(length=255), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('message_type', sa.Enum('FORM', 'PLAIN_TEXT', 'UNKNOWN', name='messagetype'), nullable=False),
    sa.Column('parsed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_table('check_ins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('raw_message_id', sa.Integer(), nullable=True),
    sa.Column('callsign', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('county', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('mode', sa.String(length=100), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('parse_status', sa.Enum('AUTO', 'MANUAL_REVIEW', 'MANUALLY_ENTERED', name='parsestatus'), nullable=False),
    sa.Column('timing_status', sa.Enum('ON_TIME', 'EARLY', 'LATE', name='timingstatus'), nullable=False),
    sa.Column('is_new_member', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['raw_message_id'], ['raw_messages.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['net_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('check_ins')
    op.drop_table('raw_messages')
    op.drop_table('members')
    # ### end Alembic commands ###
