"""add roster tables

Revision ID: f5b2383f6dd3
Revises: dbf241960f48
Create Date: 2026-04-20 14:10:53.780113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5b2383f6dd3'
down_revision: Union[str, None] = 'dbf241960f48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roster_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subject_template', sa.Text(), nullable=False),
    sa.Column('header_template', sa.Text(), nullable=False),
    sa.Column('welcome_template', sa.Text(), nullable=False),
    sa.Column('comments_template', sa.Text(), nullable=False),
    sa.Column('footer_template', sa.Text(), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roster_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'approved', 'sent', 'skipped', name='rosterstatus'), nullable=False),
    sa.Column('content_subject', sa.Text(), nullable=False),
    sa.Column('content_header', sa.Text(), nullable=False),
    sa.Column('content_welcome', sa.Text(), nullable=False),
    sa.Column('content_comments', sa.Text(), nullable=False),
    sa.Column('content_footer', sa.Text(), nullable=False),
    sa.Column('map_url', sa.String(length=500), nullable=True),
    sa.Column('drafted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['net_sessions.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['roster_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    # ### end Alembic commands ###

    # Seed default roster template for W0NE net
    op.execute(
        """
        INSERT INTO roster_templates (name, subject_template, header_template, welcome_template, comments_template, footer_template, lead_time_days, is_default)
        VALUES (
            'W0NE Net Roster',
            'W0NE Winlink Net Roster — {{ date }}',
            'W0NE Winlink Net Roster for {{ day_of_week }}, {{ date }}{% if time %} at {{ time }} UTC{% endif %}.
Net Control: {{ net_control }}
{% if activity_title %}Activity: {{ activity_title }}{% endif %}
Total Check-ins: {{ total_count }}',
            '{% for m in new_members %}Welcome to the W0NE Winlink Net, {{ m.name }} ({{ m.callsign }})!
{% endfor %}',
            '{% for c in checkins %}{% if c.comments %}{{ c.callsign }} ({{ c.name }}): {{ c.comments }}
{% endif %}{% endfor %}',
            '{% if next_week_preview %}Next week: {{ next_week_preview }}
{% endif %}{% if map_url %}Check-in map: {{ map_url }}
{% endif %}73 de W0NE',
            1,
            1
        )
        """
    )


def downgrade() -> None:
    op.execute("DELETE FROM roster_templates WHERE name = 'W0NE Net Roster'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roster_logs')
    op.drop_table('roster_templates')
    # ### end Alembic commands ###
